### ISSUE TITLE
Importing keys from string

### ISSUE THREAD

**Issue by CDespeaux** [Snooz82/robotframework-crypto#11]
More of a question than an issue...  I am looking at using this to manage/encrypt user ids and passwords for some test automation I am working on.  In order to import my keys from saved strings, it seems like I have to write some Python code that imports CryptoLibrary, instantiates an instance of CryptoUtility, sets password (for the private key), and then calls set_private_key (passing the JSON string) and probably something similar for the public key.  Does that sound right or am I way off base?  I'm rather new to Python.  Otherwise, it seems like I'd have to automate these interactive prompts, which I'm not sure if expect can handle or not.  Thanks in advance for your response.

**Comment by Snooz82** [comment]
Hi,

Could you describe a bit more what you want to do?

You are automating stuff with RobotFramework? 

Normally no python code has to be written.
There is a command line tool to encrypt data and then you can use CryptoLibrary within Robot Framework to decrypt these data.

**Comment by CDespeaux** [comment]
So I generated a key pair and saved the strings representing the private and public keys.  My automation runs in a virtual environment so I was thinking I needed to export the keys to files using the strings since my environment is refreshed on each run.  I guess I just don't understand how it finds the keys.  Maybe the key is this imports.resource file that your example shows, but I have no idea what's in that file.  I did write some code that imports your library and exports the public and private keys, which I see get written in the keys directory but when I run robot the "Get Decrypted Text" keyword fails with "AttributeError: No private key known or found in file. Generate private key first!".  How do I export the keys from the saved strings without using the interactive thing with prompts?  Weird thing is I can run my script standalone after deleting the keys with python -m CryptoLibraty and then use python -m CryptoLibrary and decrypt my text with it, so it seems my code does work?  This is essentially what I wrote, which I would be more than happy to throw out if there is a better way:

import os
import base64
import CryptoLibrary

public_key = "FTaR+wyA8hyGMUpy4bYl3vLBbKMQzEMKvuALaF32NX8="
private_key_password = os.environ.get('PRIVATE_KEY_PASSWORD')
private_key = '''{"private_key": "LUvD5OYFqfSuvjbbDcoMMwc4wlA0iuEDmLR60qPOg4a/D80cMyIDKjwowBYNzRVR1gfPrM/ImckHqjq0gEBCOKLo3gfFEJfn", "salt": "uTxX0u3x/ZjBAkOvdZUxkw==", "ops": 3, "mem": 268435456}'''
crypto = CryptoLibrary.CryptoUtility()
crypto.set_public_key(public_key)
crypto.export_public_key_to_file()
crypto.password = base64.b64decode(private_key_password).decode('ascii')
crypto.set_private_key(private_key)
crypto.export_private_key_to_file()

**Comment by CDespeaux** [comment]
I found part of my problem.  It was a decryption exception though the error that comes out is misleading and makes you believe it couldn't find the private key.  My environment variable that contains the private key password was base64 encoded, so I need to decode it at some point.  I just verified that the Get Decrypted Text keyword works if I set it to the password in plain text.

I think I will still need to have some code to export the public and private keys from a string.  Otherwise, I'm going to have to hard-code where to copy them to which I think is kind of an ugly solution.  

It would be nice if the CryptoLibrary initialization supported an optional argument that tells it where to find the keys.  Then I could just stick them in a keys folder and just give it the directory location.  Unless I'm missing something, I think you can ignore this issue/question at this point.

The only other suggestion might be to not hide the decryption exception and/or change the misleading error message.  Thanks!

**Comment by Snooz82** [comment]
Hi,

That is a good idea.
let me check if i can fix this very quickly.

**Comment by Snooz82** [comment]
@CDespeaux 
I hope i improved it a bit for you with Version 0.2.4.

`pip install -U robotframework-crypto`

Now you can set `key_path` as an argument when you import the Library.

like 
```
*** Settings ***
Resource    imports.resource
Library     CryptoLibrary    key_path=/Source/keys/    variable_decryption=True
```

And at the command line tool you can also change the path for the active session.
`Open config -> Configure key pair -> Set key path`

Please test it and give feedback.

**Comment by CDespeaux** [comment]
Appreciate you doing that but I can only download from artifactory.  I'll have to find out tomorrow what the procedure is for updating an external library.  I'll get back to you.

**Comment by CDespeaux** [comment]
Ignore my last comment..  apparently our artifactory can get remote updates.  I tested providing key_path= and it worked.  Thanks!
