### ISSUE TITLE
Plugin for Browser library

### ISSUE THREAD

**Issue by AllanMedeiros** [Snooz82/robotframework-crypto#20]
Currently Crypto lib provides a plugin for SeleniumLibrary only.
This is a request to develop a plugin for Browser / Playwright library.
Thank you.

**Comment by Snooz82** [comment]
We are discussing that in the Browser team.
currently Browser has not such a Plugin Api as Selenium has

**Comment by 4nif** [comment]
Any progress on this, would be possible to use in Browser Library?

**Comment by Snooz82** [comment]
Since 14.2.0 Browser libraries `Type Secret` and `Fill Secret` do automatic decryption if CryptoLibrary is installed and the handed over secret starts with `crypt:` 

So no "plugin" needed.

**Comment by Snooz82** [comment]
however docs have to be updated for these keywords
