### ISSUE TITLE
For loops leak secrets

### ISSUE THREAD

**Issue by Brownies** [Snooz82/robotframework-crypto#30]
The "Iteration" element leaks secrets if the iterable has a string representation of its contents. Minimal example:
```
*** Settings ***
Library         CryptoLibrary    password=password    variable_decryption=True    key_path=${CURDIR}

*** Variables ***
${secret}    crypt:BBsNlqXK9n/b8khTf02uJu0dehTe32DXUwbPMQqAYlMvu+2uCw3/RJKPjXDMcUhmyVfn2wh3Z97/frezmmstEOwg

*** Test Cases ***
Sample
    VAR    @{list}    ${secret}
    FOR    ${element}    IN    @{list}
        No Operation
    END
```
This results in
![log](https://github.com/user-attachments/assets/652ef1ca-ebe3-4862-a194-81e34d4f98e6)
Private key for decrypting the "secret": [private_key.json](https://github.com/user-attachments/files/16797634/private_key.json)

Tested with robotframework 7.0.1 and robotframework-crypto 0.3.0

**Comment by Snooz82** [comment]
Is fixed in 0.4.2
