### ISSUE TITLE
0.4.0 Breaks python versions below 3.13

### ISSUE THREAD

**Issue by trosemidmark** [Snooz82/robotframework-crypto#32]
In your CryptoLibrary/utils/__init__.py file on line 333, there is invalid quote syntax in python versions prior to 3.13.
`message.message = f'{assignment_match.group('var')} = "***"'`
Should escape the quotes around var as it thinks the string is terminated after group(.

**Comment by Snooz82** [comment]
thanks for the notice!
sorry for that!

i will fox that soony

**Comment by trosemidmark** [comment]
No problem! I thought it was odd that our pipelines just started failing over night! I appreciate the quick response. Hopefully that is the only line causing the issue! I'm starting up a quick test to validate

**Comment by trosemidmark** [comment]
Just ran a quick test. I replaced it with the following and it seemed to run fine.
`message.message = f'{assignment_match.group("var")} = "***"'`

Glad it should be a simple fix!

**Comment by Snooz82** [comment]
@trosemidmark 
Fix is released in 0.4.1

Sorry for that.
