### ISSUE TITLE
Decryption does not work in Suite Setup

### ISSUE THREAD

**Issue by SciBoard** [Snooz82/robotframework-crypto#7]
If the encrypted values are used in the **Suite Setup**, the values are not decrypted.
Example:
```
*** Settings ***
Library     CryptoLibrary  password=crypto-test  variable_decryption=True
Suite setup  Log crypto values
*** Variables ***

${string_1}=  crypt:gy9IvVKGRSEU5CquI0aPdD2Nog0FTzNRtsFdEI1N+G3m99RzoqP8a4sDCK7vrveVREVOUvsEUak=
${string_2}=  crypt:bEHB/2vYV0oiv2OcTzGARBaIqOodsYrVCuU6WnGykFHMN9KlHSjT+KGaKMJ5WErnFMY0k6V+WGMSETY=

*** Keywords ***
Log crypto values
    Log  ${string_1}
    log  ${string_2}

*** Test Cases ***
CryptoLibrary Test
    log crypto values
```
![image](https://user-images.githubusercontent.com/33685497/73166146-8de54700-40f5-11ea-9428-11d1d6957cc5.png)

**Comment by Snooz82** [comment]
Correct.
I did not implement the decryption for start_suite.
You can use the `Get Decrypted Text` in Suite Setup.

But you are right. It could be useful!
I will have a look next days.

**Comment by SciBoard** [comment]
Hey Renè,
Thank's for the hint. I've change to Get Decrypted Text. It works fine for the Suite Setup, but I've got error in the test case. 
```
*** Settings ***
Library     CryptoLibrary  password=crypto-test  variable_decryption=True
Suite setup  Log crypto values

*** Variables ***
${string_1}=  crypt:gy9IvVKGRSEU5CquI0aPdD2Nog0FTzNRtsFdEI1N+G3m99RzoqP8a4sDCK7vrveVREVOUvsEUak=

*** Keywords ***
Log crypto values
    ${str_1}=   Get Decrypted Text  ${string_1}
    Log  ${str_1}

*** Test Cases ***
CryptoLibrary Test
    log crypto values
```
![image](https://user-images.githubusercontent.com/33685497/73186631-622b8680-4120-11ea-9a78-1c1582e1e83c.png)

**Comment by Snooz82** [comment]
Yes because by default it is already decrypted there.
I will try to fix this this evening.

**Comment by SciBoard** [comment]
Thank's. I've got it - just to use <br>
 `Library     CryptoLibrary  password=crypto-test  variable_decryption=False`

**Comment by Snooz82** [comment]
If automatic variable decryption is active (Default), CryptoLibrary does the decryption on start_suite and on start_test and sets the variable into the highest scope where it was found first.

`Library    CryptoLibrary    variable_decryption=False`
