### ISSUE TITLE
Change from PyInquirer to questionary

### ISSUE THREAD

**Issue by SciBoard** [Snooz82/robotframework-crypto#8]
Now-a-day CryptoLibrary uses the **PyInquirer**, which requires **prompt-toolkit 1.0.14**. This version of promo-toolkit has conflict with actual ipython, which requires **prompt-toolkit-3.0.**. The next version of PyInquirer (2.x) will be published not so soon. 
Maybe we can use the questionary instead  https://github.com/tmbo/questionary

**Comment by Snooz82** [comment]
Great idea. Had a brief look to this after our Meetup. Looks nice!
I will see when i have time.

**Comment by josev814** [comment]
Has there been any update on this?

**Comment by Snooz82** [comment]
fixed with #12
